#!/usr/bin/env python3
import sys

NO = "Impossible"  # type: str


def solve(N: int, A: "List[int]", S: "List[str]", Q: int, U: "List[int]", V: "List[int]"):
    return


# Generated by 2.12.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    S = [next(tokens) for _ in range(N)]  # type: "List[str]"
    Q = int(next(tokens))  # type: int
    U = [int()] * (Q)  # type: "List[int]"
    V = [int()] * (Q)  # type: "List[int]"
    for i in range(Q):
        U[i] = int(next(tokens))
        V[i] = int(next(tokens))
    solve(N, A, S, Q, U, V)

if __name__ == '__main__':
    main()
